import { jsPDF } from 'jspdf';
import 'jspdf-autotable';

export const generateResultPdf = (student, exam, attempt) => {
    const doc = jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // Add Border
    doc.setDrawColor(99, 102, 241); // Primary Color
    doc.setLineWidth(1);
    doc.rect(5, 5, pageWidth - 10, doc.internal.pageSize.getHeight() - 10);

    // Header
    doc.setFontSize(24);
    doc.setTextColor(99, 102, 241);
    doc.text('EXAM RESULT CERTIFICATE', pageWidth / 2, 30, { align: 'center' });

    doc.setFontSize(12);
    doc.setTextColor(100, 116, 139);
    doc.text('This is to certify that the following student has successfully completed the examination.', pageWidth / 2, 40, { align: 'center' });

    // Student Info Section
    doc.setDrawColor(226, 232, 240);
    doc.line(20, 50, pageWidth - 20, 50);

    doc.setFontSize(14);
    doc.setTextColor(30, 41, 59);
    doc.text('STUDENT INFORMATION', 20, 60);

    doc.autoTable({
        startY: 65,
        head: [['Field', 'Details']],
        body: [
            ['Student Name', student.name],
            ['Email Address', student.email],
            ['Student ID', student.id.toUpperCase()]
        ],
        theme: 'striped',
        headStyles: { fillColor: [99, 102, 241] },
        styles: { fontSize: 11, cellPadding: 5 }
    });

    // Exam Details Section
    const finalY = doc.lastAutoTable.finalY + 15;
    doc.text('EXAMINATION DETAILS', 20, finalY);

    const percentage = ((attempt.score / exam.questions.length) * 100).toFixed(2);
    const date = new Date(attempt.completedAt).toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit'
    });

    doc.autoTable({
        startY: finalY + 5,
        head: [['Exam Title', 'Total Questions', 'Correct Answers', 'Percentage', 'Date']],
        body: [
            [exam.title, exam.questions.length, attempt.score, `${percentage}%`, date]
        ],
        theme: 'grid',
        headStyles: { fillColor: [79, 70, 229] },
        styles: { fontSize: 11, cellPadding: 5 }
    });

    // Performance Summary
    const summaryY = doc.lastAutoTable.finalY + 20;
    doc.setFontSize(16);
    doc.setTextColor(percentage >= 50 ? [22, 163, 74] : [220, 38, 38]); // Success or Danger
    doc.text(`RESULT: ${percentage >= 50 ? 'PASS' : 'FAIL'}`, pageWidth / 2, summaryY, { align: 'center' });

    // Footer
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by Exam Management System', pageWidth / 2, doc.internal.pageSize.getHeight() - 20, { align: 'center' });
    doc.text(`Certificate ID: EMS-${Math.random().toString(36).substr(2, 6).toUpperCase()}`, pageWidth / 2, doc.internal.pageSize.getHeight() - 15, { align: 'center' });

    // Save PDF
    doc.save(`${student.name.replace(/\s+/g, '_')}_${exam.title.replace(/\s+/g, '_')}_Result.pdf`);
};
